# Generated by Django 5.0.7 on 2024-11-01 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0021_rename_addominal_pain_examen_dolor_abdominal_intenso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='Tiempo_deteccion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 1, 22, 22, 28, 296956, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
