# Generated by Django 5.0.7 on 2024-11-12 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0022_examen_tiempo_deteccion_alter_paciente_token_expires'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name': 'examen', 'verbose_name_plural': 'exámenes'},
        ),
        migrations.AlterModelOptions(
            name='historial',
            options={'verbose_name': 'historial', 'verbose_name_plural': 'historiales'},
        ),
        migrations.AlterField(
            model_name='examen',
            name='Dolor_abdominal_intenso',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 0, 30, 14, 645602, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
