# Generated by Django 5.0.7 on 2024-11-13 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediagnostico', '0023_alter_examen_options_alter_historial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historial',
            options={},
        ),
        migrations.AlterField(
            model_name='examen',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='token_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 11, 20, 52, 986035, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
